CREATE TABLE IF NOT EXISTS "comments"(  
    "id" SERIAL PRIMARY KEY,
    "post_id" SERIAL NOT NULL,
    "user_id" SERIAL NOT NULL,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);