services:

  app-service:
    build:
      context: .
      args:
          GO_IMAGE_NAME: ${GO_IMAGE_NAME}
          GO_IMAGE_VERSION: ${GO_IMAGE_VERSION}
    container_name: app-service
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db-service
      - redis-service
    entrypoint:
      - air
    env_file:
      - .env
    volumes:
      - ./:/home/app


  db-service:
    image: postgres:17.2-alpine3.21
    container_name: db-service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    restart: unless-stopped


  redis-service:
    image: redis:8.0-M03-alpine3.21
    restart: unless-stopped
    container_name: redis-service
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    command: redis-server --save 60 1 --loglevel warning


volumes:
  db-data: